function [country, beer_servings, wine_servings, spirit_servings, total_litres_of_pure_alcohol] = import_csv(filename, delimiter, startRow)
% IMPORT_CSV Génère les vecteurs colonnes présents dans un fichier csv

% Auto-generated by MATLAB on 2017/11/15 21:11:44 and modified by Olivier
% Moitroux and Pierre Hockers

% Initialize variables.
if nargin == 1
    delimiter = ',';
    startRow = 2;
end


% Format for each line of text:
%   column1: text (%s)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
formatSpec = '%s%f%f%f%f%[^\n\r]';

% Open the text file.
fileID = fopen(filename,'r');

% Read columns of data according to the format.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

% Close the text file.
fclose(fileID);

% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included.

% Allocate imported array to column variable names
country = dataArray{:, 1};
beer_servings = dataArray{:, 2};
spirit_servings = dataArray{:, 3};
wine_servings = dataArray{:, 4};
total_litres_of_pure_alcohol = dataArray{:, 5};

% Clear temporary variables
% clearvars filename delimiter startRow formatSpec fileID dataArray ans;

end

